### ISSUE TITLE
Add description of servers to openapi spec

### ISSUE THREAD

**Issue by matthewtrask** [Geocodio/openapi-spec#1]
The spec looks great! Glad to see it published. If possible, adding a `description` to the servers object would add even more clarity :)

**Comment by MiniCodeMonkey** [comment]
Thanks for the suggestion Matt! I'll get right at it. Would also love to add a lot more `example` keys throughout.

**Comment by MiniCodeMonkey** [comment]
Fixed with https://github.com/Geocodio/openapi-spec/commit/01264e06d055013ec9df90df191e214a18a578dc
